apiVersion: v1
kind: Pod
metadata:
  name: message-broker
  labels:
    name: brokerMessage
spec:
  containers:
  - name: redis
    image: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  

