apiVersion: v1
kind: Pod
metadata:
  name: web-frontend
  labels:
    name: web
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 81
